import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import UserProvider from "@/context/UserContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Raksha",
  description: "Generated by create next app",
};
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import DoctorProvider from "@/context/doctorContext";
import PathlabProvider from "@/context/pathlabContext";

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <PathlabProvider>
        <UserProvider>
          <DoctorProvider>
            {children}
            <ToastContainer position="top-right" autoClose={3000} />
          </DoctorProvider>
        </UserProvider>
        </PathlabProvider>
      </body>
    </html>
  );
}
